name: build

on: 
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", 3.1, 3.2, 3.3, 3.4]
        rails: [rails_6, rails_6_1, rails_7, rails_7_1, rails_7_2, rails_8]
        twilio: [twilio_6, twilio_7]
        exclude:
          - rails: rails_7_2 # Rails 7.2 requires Ruby 3.1
            ruby: "3.0"
          - rails: rails_6 # minitest from this version doesn't supporter Ruby 3.4
            ruby: 3.4
          - rails: rails_6_1 # minitest from this version doesn't supporter Ruby 3.4
            ruby: 3.4
          - rails: rails_7 # minitest from this version doesn't supporter Ruby 3.4
            ruby: 3.4
          - rails: rails_8 # Rails 8 requires 3.2
            ruby: "3.0"
          - rails: rails_8 # Rails 8 requires 3.2
            ruby: 3.1
    env:
      BUNDLE_GEMFILE: gemfiles/${{matrix.rails}}__${{ matrix.twilio }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
